import LegalPage from './LegalPage'
import { COMPANY } from '../config/legal'

const sections = [
  {
    heading: 'Our commitment',
    body: `Your privacy matters to us. This Privacy Policy explains what personal information ${COMPANY.legalName} collects when you use carvaanholidays.com, how we use it, and the choices you have. By using the Website you consent to the practices described below.`,
  },
  {
    heading: 'Information we collect',
    body: (
      <>
        <p>We collect information you give us directly and information generated by your interaction with the Website:</p>
        <ul>
          <li><strong>Personal details</strong> — name, email, phone number, and address you provide when submitting an enquiry, booking a trip, or contacting us.</li>
          <li><strong>Travel details</strong> — destination interest, dates, number of travellers, preferences, and any special requirements you share.</li>
          <li><strong>Payment details</strong> — processed securely by our payment gateway partners. We do not store card numbers, CVV, or full bank details on our servers.</li>
          <li><strong>Technical data</strong> — IP address, browser type, device information, pages visited, and cookies used to keep the site functional and secure.</li>
        </ul>
      </>
    ),
  },
  {
    heading: 'How we use your information',
    body: (
      <ul>
        <li>To process your enquiries, quotes, bookings, and payments.</li>
        <li>To send booking confirmations, itineraries, invoices, and travel updates.</li>
        <li>To answer your questions and provide customer support before, during, and after your trip.</li>
        <li>To share offers, promotions, and travel inspiration by email, SMS, or WhatsApp — only if you have opted in. You can opt out any time.</li>
        <li>To improve the Website and our services through anonymised analytics.</li>
        <li>To comply with legal, tax, and regulatory obligations.</li>
      </ul>
    ),
  },
  {
    heading: 'Sharing your information',
    body: (
      <>
        <p>We share the minimum information necessary with:</p>
        <ul>
          <li><strong>Travel service providers</strong> — hotels, airlines, transport operators, and local partners — so they can deliver the service you booked.</li>
          <li><strong>Payment gateway partners</strong> — to process transactions securely.</li>
          <li><strong>Analytics and communication tools</strong> — e.g. email / SMS / WhatsApp providers we use to deliver messages.</li>
          <li><strong>Government / regulatory authorities</strong> — where required by law.</li>
        </ul>
        <p>We never sell your personal data to third parties.</p>
      </>
    ),
  },
  {
    heading: 'Cookies',
    body: 'We use cookies and similar technologies to keep the Website functional (e.g. remembering that you dismissed a popup), to measure usage, and to improve the experience. You can control cookies through your browser settings. Disabling cookies may limit some features.',
  },
  {
    heading: 'Data retention',
    body: 'We keep your personal information only for as long as needed to provide our services and to comply with legal, accounting, or reporting obligations. Enquiry data is typically retained for 3 years, transaction records for 8 years (as required by Indian tax laws).',
  },
  {
    heading: 'Your rights',
    body: (
      <>
        <p>You have the right to:</p>
        <ul>
          <li>Access the personal information we hold about you.</li>
          <li>Ask us to correct inaccurate information.</li>
          <li>Ask us to delete your information, subject to any legal obligations to retain it.</li>
          <li>Withdraw consent for marketing communications at any time.</li>
        </ul>
        <p>
          To exercise any of these rights, email us at{' '}
          <a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a>.
        </p>
      </>
    ),
  },
  {
    heading: 'Security',
    body: 'We use industry-standard security measures — HTTPS, encrypted payment gateways, and access controls — to protect your information. No online transmission is ever 100 % secure, so we ask you to keep your account credentials confidential and to report any suspected misuse to us immediately.',
  },
  {
    heading: 'Changes to this policy',
    body: 'We may update this Privacy Policy from time to time. Any material changes will be posted on this page with a new "Last updated" date. Please review it periodically.',
  },
  {
    heading: 'Contact us',
    body: (
      <div className="legal__callout">
        <strong>Privacy queries</strong>
        <p>
          {COMPANY.legalName}<br />
          {COMPANY.address}<br />
          Phone: <a href={`tel:${COMPANY.phone}`}>{COMPANY.phone}</a> · Email: <a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a>
        </p>
      </div>
    ),
  },
]

export default function Privacy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title={<><em>Privacy</em> Policy</>}
      updated={COMPANY.policiesUpdated}
      sections={sections}
    />
  )
}
